### PR TITLE
AuthDBProperties - bug fix to get resource file

### LINKED ISSUE #90: Fix bug in AuthDBProperties when reading server.conf
Recent refactoring of AuthDBConnection introduced a bug because it replaced a method for reading a resource as a stream with reading it as a file stream, the latter is not working reliably despite unit tests indicating that it was working.  Looks like we also need integration tests (but that is not the immediate purpose of a fix for this bug).

### PR DESCRIPTION
**Pull request by darrenleeweber**
Fix #90 

This fix was working in an integration test (using it in the TB-scripts to run conversions).

### CODE REVIEW

File: conversiontracerbullet/src/main/java/org/stanford/AuthDBProperties.java [hunk 1]
```diff
@@ -19,22 +16,22 @@
...
 
-    private static final String DEFAULT_CONFIG_FILE = "/server.conf";
+    private static final String PROPERTY_RESOURCE = "/server.conf";
 
     private String server = null;
     private String service = null;
     private String userName = null;
     private String userPass = null;
-    private String propertyFile = null;
+    private Properties properties = null;
```
Comment (ndushay) [inline conversiontracerbullet/src/main/java/org/stanford/AuthDBProperties.java]: would it make more sense to pass "properties" as an argument to initDataSourceProperties(), since we call it in the constructor(s) and we must instantiate properties before calling it?

File: conversiontracerbullet/src/test/java/org/stanford/AuthDBPropertiesTest.java [hunk 2]
```diff
@@ -28,23 +29,24 @@
...
         authProps = new AuthDBProperties();
-        // Use private method to get the server.conf file path
-        Field f = AuthDBProperties.class.getDeclaredField("propertyFile");
-        f.setAccessible(true);
-        propertyFile = (String) f.get(authProps);
-        serverConfFile = new File(propertyFile);
-        // Use private method to get the server.conf properties
-        Method m = AuthDBProperties.class.getDeclaredMethod("loadDataSourceProperties", String.class);
+
+        Method m = AuthDBProperties.class.getDeclaredMethod("loadPropertyResource");
```
Comment (ndushay) [inline conversiontracerbullet/src/test/java/org/stanford/AuthDBPropertiesTest.java]: Am I misunderstanding this?   It seems like this line is calling the class method to get data, and then we are matching below (testConstructor, testConstructorWithString) if the data we got using the same method, but called differently (directly rather than with "getDeclaredMethod"), is equal.  I would always expect the same method to give the same result, given the same data ...

It looks like the test was that way before this PR ... just thinking it might be better to check the loaded properties against hardcoded known value strings here.

File: conversiontracerbullet/src/test/resources/server.conf [hunk 3]
```diff
@@ -1,4 +1,4 @@
-SERVER=libdb.stanford.edu
+SERVER=db.example.com
```
Comment (ndushay) [inline conversiontracerbullet/src/test/resources/server.conf]: 👍

File: conversiontracerbullet/src/main/java/org/stanford/AuthDBProperties.java (hunk 1 above)
Comment (darrenleeweber) [inline conversiontracerbullet/src/main/java/org/stanford/AuthDBProperties.java]: No.  It is initialized by two different methods and those methods are specific to the type of constructor called.  Thereafter, it's available to the init method.  This is optimal already.

File: conversiontracerbullet/src/test/java/org/stanford/AuthDBPropertiesTest.java (hunk 2 above)
Comment (darrenleeweber) [inline conversiontracerbullet/src/test/java/org/stanford/AuthDBPropertiesTest.java]: If the data in the properties file changes without changing any hard-coded values in the test, the test breaks.  There are various ways to do this, for sure, and this one suffices to get the job done.  If using fixed values is required to merge this, we can do that, but it just shifts that data into two places (the resource file and the test, both of which only exist in the tests).

Comment (darrenleeweber) [inline conversiontracerbullet/src/test/java/org/stanford/AuthDBPropertiesTest.java]: Yet another way to do this is to `assertNotNull`, but that's less specific (although less fragile and does not depend on checking specific values).

File: conversiontracerbullet/src/main/java/org/stanford/AuthDBProperties.java (hunk 1 above)
Comment (darrenleeweber) [inline conversiontracerbullet/src/main/java/org/stanford/AuthDBProperties.java]: FYI, I went down that road before and ended up where it is now.  For example, if it gets passed, we get pseudo-code like this:
```
initProps( propertyFile ) {
  if propertyFile == null
    properties = loadResourceProperties
  else
    properties = loadPropertiesFile( propertyFile )
  ...
}
```
So, putting the initializers in the constructors avoids this null check.  I hope that helps?

Comment (ndushay) [inline conversiontracerbullet/src/main/java/org/stanford/AuthDBProperties.java]: I meant pass it the Properties object itself -- the result of `loadPropertiesFile()` or `loadResourceProperties()`

File: conversiontracerbullet/src/test/java/org/stanford/AuthDBPropertiesTest.java (hunk 2 above)
Comment (ndushay) [inline conversiontracerbullet/src/test/java/org/stanford/AuthDBPropertiesTest.java]: I'm ok leaving this as is;  

It's true there is a  maintenance cost incurred that if you change the data being used for tests, you have to change the hardcoded data in the tests ... but in my experience it is still better to test for actual values than test a method's results against ... the same method's results.

File: conversiontracerbullet/src/main/java/org/stanford/AuthDBProperties.java (hunk 1 above)
Comment (darrenleeweber) [inline conversiontracerbullet/src/main/java/org/stanford/AuthDBProperties.java]: Oh, yes, that's possible.  The next consideration is how easy the class is to test.  As it is, those methods are easier to test (or use in tests).  I guess that's why it is this way, rather than those loading methods be void methods.  At some point while developing tests, it was easier if they return Properties.  It's reasonable to request this, but it could entail more work to change tests as well.  Not sure we really gain much?  Perhaps we can pair on this rather than play github comment tennis?

File: conversiontracerbullet/src/test/java/org/stanford/AuthDBPropertiesTest.java (hunk 2 above)
Comment (darrenleeweber) [inline conversiontracerbullet/src/test/java/org/stanford/AuthDBPropertiesTest.java]: If the tests could get direct access to the resource file without using the class...  Or if the tests could create the resource file dynamically...  but that's not possible, right?  Or it's more work.  Either way, there are tradeoffs and resource files have already given me a run around, in more ways than one (better explained in person than go on and on about it here).

File: conversiontracerbullet/src/test/resources/server.conf (hunk 3 above)
Comment (darrenleeweber) [inline conversiontracerbullet/src/test/resources/server.conf]: Notice how this change to the resource file entailed no consequent changes in the test code, because the test code gets access to this resource file.  Yes, it gets it via the class under test.  Maybe there's a better way to do that?  (My java-test practices are very rusty, but this PR is a good try.)

File: conversiontracerbullet/src/main/java/org/stanford/AuthDBProperties.java (hunk 1 above)
Comment (darrenleeweber) [inline conversiontracerbullet/src/main/java/org/stanford/AuthDBProperties.java]: If I get your point correctly, it seems your requesting changes like the following:
```java
            // lines 84 - 85 are:
           Properties props = new Properties();
           props.load(iStream);
           // they are replaced by using the instance var
           properties.load(iStream);
```

I'll try that and see what happens.

Comment (darrenleeweber) [inline conversiontracerbullet/src/main/java/org/stanford/AuthDBProperties.java]: OK, the new commit might be what your proposing.

File: conversiontracerbullet/src/test/java/org/stanford/AuthDBPropertiesTest.java (hunk 2 above)
Comment (darrenleeweber) [inline conversiontracerbullet/src/test/java/org/stanford/AuthDBPropertiesTest.java]: The latest commit gets the resource file "directly" in the tests.
